//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManager.Entities
{
	using System;
	using System.Data.Entity;
	using System.Data.Entity.Infrastructure;

	public partial class ProjectManagerEntities : DbContext
	{
		static ProjectManagerEntities _context;
		public static ProjectManagerEntities GetContext()
		{
			if (_context == null)
				_context = new ProjectManagerEntities();
			return _context;
		}
		public ProjectManagerEntities()
						: base("name=ProjectManagerEntities")
		{
		}

		protected override void OnModelCreating(DbModelBuilder modelBuilder)
		{
			throw new UnintentionalCodeFirstException();
		}

		public virtual DbSet<Project> Projects { get; set; }
		public virtual DbSet<ProjectRole> ProjectRoles { get; set; }
		public virtual DbSet<ProjectTask> ProjectTasks { get; set; }
		public virtual DbSet<ProjectUser> ProjectUsers { get; set; }
		public virtual DbSet<User> Users { get; set; }
		public virtual DbSet<UserInfo> UserInfoes { get; set; }
	}
}
